### ISSUE TITLE
Error outside of..

### ISSUE THREAD

**Issue by nodoubtman** [yumetodo/google-photos-album-image-url-fetch#17]
Hello I'm trying with my raspberry pi 3, and i got his error:

import * as GooglePhotosAlbum from '../src/index';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

Can you help?

Thanks.
Marc.

**Comment by yumetodo** [comment]
`import` is ESM syntax. enable ESM support or use `const GooglePhotosAlbum  = require("google-photos-album-image-url-fetch")` instead.

**Comment by nodoubtman** [comment]
> 
> 
> `import` is ESM syntax. enable ESM support or use `const GooglePhotosAlbum = require("google-photos-album-image-url-fetch")` instead.

Thank you so much :))

**Comment by yumetodo** [comment]
Don't forget to close this issue when you resolve your problem.
